#!/bin/bash

yum -y groupinstall "Japanese Support" 
sed -i.org -e "s/en_US.UTF-8/ja_JP.UTF-8/g" /etc/sysconfig/i18n

rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
#iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
service iptables save

yum install -y emacs.x86_64 git-all.noarch
