#!/bin/bash

# Disable tunnelled clear text passwords
sed -i.org -e "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
service ssh restart

# Change to JST time zone
rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Install basic tools
apt-get install -y curl vim make git emacs sudo ufw 

# Configure Linux Firewall
# --- CAUTION --- Deny access from public address
ufw allow from 10.0.0.0/8
echo y | ufw enable

# DNS server for softlayer local domain
cat <<EOF >> /etc/resolv.conf
nameserver 67.228.254.4
nameserver 67.228.255.5
EOF

# For Chef Ohai plugin
mkdir -p /etc/chef/ohai/hints && touch ${_}/softlayer.json

