#!/bin/bash

# Disable tunnelled clear text passwords
#sed -i.org -e "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
#service ssh restart
# Change to Japanese locale
#aptitude -y install language-pack-ja-base language-pack-ja
#update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

# Configure Linux Firewall
# --- CAUTION --- Change to deny access from public address
#ufw allow from 10.0.0.0/8
#ufw allow ssh/tcp
#ufw allow http/tcp
#echo y | ufw enable

# Change to JST time zone
rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Install basic tools
apt-get install -y curl vim make git emacs23 python

# add user
#useradd -m minion
#cp -r /root/.ssh /home/minion
#chown -R minion:minion /home/minion/.ssh
#echo "minion ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/minion
#chmod 440 /etc/sudoers.d/minion

