#!/bin/bash

# Disable tunnelled clear text passwords
sed -i.org -e "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
service ssh restart

# Change to Japanese locale
aptitude -y install language-pack-ja-base language-pack-ja
update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

# Change to JST time zone
rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Configure Linux Firewall
# --- CAUTION --- Change to deny access from public address
ufw allow from 10.0.0.0/8
echo y | ufw enable

# Install basic tools
apt-get install -y curl vim make git emacs23

# DNS server for softlayer local domain
cat <<EOF >> /etc/resolv.conf
nameserver 67.228.254.4
nameserver 67.228.255.5
EOF

# Install CHEF & Configure
CHEF_WORK=/root/chef
CHEF_COOK=/var/chef/cookbooks
mkdir ${CHEF_WORK}
curl -L https://www.opscode.com/chef/install.sh > ${CHEF_WORK}/install.sh
bash ${CHEF_WORK}/install.sh -v 12.5 -d ${CHEF_WORK}
knife cookbook create dummy -o ${CHEF_COOK}

# Download the cookbook & apply
git -C ${CHEF_COOK} clone https://github.com/takara9/wordpress01
#chef-solo -o memcache01

